# Copied from ../../docker-compose.yaml
# Please keep in synch :-)

version: '2.3'
services:
  xl-deploy:
    image: xl-docker.xebialabs.com:443/xl-deploy:8.5.0-alpha.55
    ports:
    - "4516:4516"
    volumes:
    - ../../docker/xld/conf/deployit-license.lic:/opt/xebialabs/xl-deploy-server/conf/deployit-license.lic:ro
    - ../../docker/xld/hotfix/plugins:/opt/xebialabs/xl-deploy-server/hotfix/plugins:ro
    # Workaround for bug (in XL Deploy?) that causes plugins to not function correctly if loaded from within the container
    - ../../docker/volumes/xld/plugins:/opt/xebialabs/xl-deploy-server/plugins
    environment:
    - ADMIN_PASSWORD=admin

  xl-release:
    image: xl-docker.xebialabs.com:443/xl-release:8.5.0-alpha.41
    ports:
    - "5516:5516"
    depends_on:
    - xl-deploy
    volumes:
    - ../../docker/xlr/conf/xl-release-license.lic:/opt/xebialabs/xl-release-server/conf/xl-release-license.lic:ro
    - ../../docker/xlr/hotfix:/opt/xebialabs/xl-release-server/hotfix:ro
    - ./plugins/:/opt/xebialabs/xl-release-server/plugins/:ro
    - ./xl-impact/xl-release.conf:/opt/xebialabs/xl-release-server/conf/xl-release.conf:ro
    # - ~/Code/xlr-jenkins-pipeline-radar-plugin/src/main/resources:/opt/xebialabs/xl-release-server/ext:rw # Uncomment this line when developing plugin locally
    environment:
    - ADMIN_PASSWORD=admin

  xl-cli:
    build: ../../docker/xl-cli
    depends_on:
    - xl-deploy
    - xl-release
    command: ["apply", "-v", "--xl-deploy-url", "http://xl-deploy:4516/", "--xl-release-url", "http://xl-release:5516/", "-f", "/data/config/configure-xl-devops-platform.yaml"]
    volumes:
    - ../..:/data:ro

  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    privileged: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment: # warning this potentially opens up a security hole :)
      - AUTH=1
      - BUILD=1
      - COMMIT=1
      - CONTAINERS=1
      - EVENTS=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PING=1
      - PLUGINS=1
      - POST=1
      - SECRETS=1
      - SERVICES=1
      - SWARM=1
      - SYSTEM=1
      - TASKS=1
      - VERSION=1
      - VOLUMES=1

  jenkins:
    image: jenkinsci/blueocean:latest
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - ./jenkins_home:/var/jenkins_home
    environment:
    - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
