
apiVersion: xl-release/v1beta1
kind: Templates
spec:
- directory: JenkinsWorld
  children:
  - name: Track Jenkins pipeline and trigger feature delivery
    type: xlrelease.Release
    scheduledStartDate: '2018-08-17T07:00:00+0000'
    variables:
    - key: pipeline
      type: xlrelease.StringVariable
      label: Jenkins pipeline
      description: The name of the pipeline to track in Jenkins
    - key: branch
      type: xlrelease.StringVariable
      label: Branch
      description: Branch of the pipeline in Jenkins
      value: master
    - key: buildNumber
      type: xlrelease.StringVariable
      label: Build number
      description: Build number of the pipeline build in Jenkins
    - key: pipelineData
      type: xlrelease.StringVariable
      requiresValue: false
      showOnReleaseStart: false
    - key: pipeline.check.codecoverage
      type: xlrelease.BooleanVariable
      requiresValue: false
      label: Check code coverage
      description: Scans the pipeline for Code Coverage
      value: true
    - key: pipeline.check.apitests
      type: xlrelease.BooleanVariable
      requiresValue: false
      label: Check API tests
      description: Scans the pipeline for API tests
      value: true
    - key: pipeline.check.uitests
      type: xlrelease.BooleanVariable
      requiresValue: false
      label: Check UI tests
      description: Scans the pipeline for UI tests
      value: true
    - key: pipeline.check.integrationtests
      type: xlrelease.BooleanVariable
      requiresValue: false
      label: Check integration tests
      description: Scan pipeline for integration tests
      value: true
    - key: deliveryStrategy
      type: xlrelease.StringVariable
      label: Delivery strategy
      description: Action to perform when the pipeline completes successfully
      valueProvider:
          type: xlrelease.ListOfStringValueProviderConfiguration
          values:
          - Start Feature Delivery Process
          - Add Feature to Release Train
          - No Action
    description: The one that starts a feature release.
    tags:
    - pipeline radar
    abortOnFailure: true
    phases:
    - name: Connect to Jenkins
      type: xlrelease.Phase
      color: '#999999'
      tasks:
      - name: Import pipeline
        type: xlrelease.SequentialGroup
        tasks:
        - name: 'Track Jenkins pipeline job #${buildNumber}'
          type: jenkins.PipelineTracker
          pipelineName: ${pipeline}
          branch: ${branch}
          buildNumber: ${buildNumber}
          pipelineData: ${pipelineData}
        - name: Check compliance
          type: jenkins.Compliance
          codeCoverage: ${pipeline.check.codecoverage}
          apiTests: ${pipeline.check.apitests}
          uiTests: ${pipeline.check.uitests}
          integrationTests: ${pipeline.check.integrationtests}
          pipelineData: ${pipelineData}
    - name: Feature delivery
      type: xlrelease.Phase
      color: '#08B153'
      tasks:
      - name: Start Feature Delivery Process
        type: xlrelease.CreateReleaseTask
        precondition: releaseVariables['deliveryStrategy'] == "Start Feature Delivery Process"
        newReleaseTitle: Release process for ${pipeline} (${branch})
        # templateId: // Error: Release [Applications/Folder4c6fbb2f2a3c4bffacf25703f841f620/Release7f1e882f79a84a1db14eaa1f7494a2c4] does not exist in the repository or archive. It may have been moved or deleted
        # folderId: Applications/Folder4c6fbb2f2a3c4bffacf25703f841f620
        templateVariables:
        - key: jenkinsPipeline
          type: xlrelease.StringVariable
          label: Jenkins pipeline
          description: The name of the pipeline in Jenkins
          value: ${pipeline}
        - key: branch
          type: xlrelease.StringVariable
          label: Branch
          description: Pipeline branch in Jenkins
          value: ${branch}
        - key: buildNumber
          type: xlrelease.StringVariable
          label: Build number
          description: The build number in Jenkins
          value: ${buildNumber}
      - name: Add Feature to Release Train
        type: release.RegisterRelease
        precondition: releaseVariables['deliveryStrategy'] == "Add Feature to Release Train"
        targetRelease: Release train
        tag: Features
        title: 'Feature #${buildNumber}'
    releaseTriggers:
    - name: Track Jenkins Pipeline
      type: jenkins.Trigger
      releaseTitle: 'Jenkins pipeline for [PIPELINE_NAME] #${buildNumber}'
      enabled: false
      variables:
      - key: pipeline
        type: xlrelease.StringVariable
        value: ${pipeline}
      - key: branch
        type: xlrelease.StringVariable
        value: ${branch}
      - key: buildNumber
        type: xlrelease.StringVariable
        value: ${buildNumber}
      - key: pipelineData
        type: xlrelease.StringVariable

      - key: pipeline.check.codecoverage
        type: xlrelease.BooleanVariable
        value: true
      - key: pipeline.check.apitests
        type: xlrelease.BooleanVariable
        value: true
      - key: pipeline.check.uitests
        type: xlrelease.BooleanVariable
        value: true
      - key: pipeline.check.integrationtests
        type: xlrelease.BooleanVariable
        value: true
      - key: deliveryStrategy
        type: xlrelease.StringVariable
        value: Start Feature Delivery Process
      pipelineName: [PIPELINE_NAME]
      branchName: [BRANCH_NAME]
     