apiVersion: xl-release/v1
kind: Templates
spec:
- name: REST-o-rant on ECS
  type: xlrelease.Release
  description: |
    This XL Release template shows how to deploy an undeploy an application to AWS ECS using XL Deploy.
  tags:
  - REST-o-rant
  - ECS
  phases:
  - name: Deploy
    color: '#ff9e3b'
    type: xlrelease.Phase
    tasks:
    - name: Ready to go?
      type: xlrelease.GateTask
      team: Release Admin
    - name: Deploy rest-o-rant application
      type: xldeploy.Deploy
      server: XL Deploy
      deploymentPackage:  REST-o-rant/AWS/rest-o-rant-ecs-service/1.0
      deploymentEnvironment: Environments/REST-o-rant/AWS
  - name: Test
    type: xlrelease.Phase
    tasks:
    - name: Test REST-o-rant
      type: xlrelease.Task
      team: Release Admin
      description: |
        The REST-o-rant app is now live on ECS!
        Check out the web site and complete this task when done.

        1. Go to the AWS console
        2. Go to the ECS section of the AWS console
        3. Go to the region to which you've deployed the ECS Fargate cluster
        4. Click on the `USERNAME-ror-ecs-cluster`
        5. Click on the `rest-o-rant-service`
        6. Select the Tasks tab
        7. Click on the first task
        8. Copy the public IP
        9. Open a new browser window to: http://PUBLICIP/
      team: Release admin
  - name: Clean up
    color: '#999999'
    type: xlrelease.Phase
    tasks:
    - name: Undeploy REST-o-rant
      type: xldeploy.Undeploy
      server: XL Deploy
      deployedApplication: Environments/REST-o-rant/AWS/rest-o-rant-ecs-service
