apiVersion: xl-deploy/v1alpha1
kind: Applications
spec:
- name: Applications/AWS
  type: core.Directory
  children:
    - name: rest-o-rant-ecs-service
      type: udm.Application
      children:
      - name: 1.0
        type: udm.DeploymentPackage
        deployables:
        - name: rest-o-rant-service
          type: aws.ecs.ServiceSpec
          serviceName: rest-o-rant-service
          desiredCount: 1
          launchType: FARGATE
          networkMode: awsvpc
          assignPublicIp: ENABLED
          cpu: 256
          memory: 1024
          # taskRole: aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS
          subnets:
          # - Name:ror-subnet-ipv4-az-1a
          # - Name:ror-subnet-ipv4-az-1b
          - subnet-3f108a77
          - subnet-ddf77dbb
          securityGroups:
          # - Name:ror-security-group
          - sg-c640c7ba
          containerDefinitions:
          # - name: rest-o-rant-web
          #   containerName: rest-o-rant-web
          #   type: aws.ecs.ContainerDefinitionSpec
          #   image: xebialabsunsupported/rest-o-rant-web:v1
          #   softMemoryLimit: 512
          #   # links:
          #   # - rest-o-rant-api
          #   portMappings:
          #   - name: port-mapping-80
          #     type: aws.ecs.PortSpec
          #     hostPort: 80
          #     containerPort: 80
          - name: rest-o-rant-api
            containerName: rest-o-rant-api
            type: aws.ecs.ContainerDefinitionSpec
            image: xebialabsunsupported/rest-o-rant-api:v1
            softMemoryLimit: 512
            portMappings:
            - name: port-mapping-8080
              type: aws.ecs.PortSpec
              hostPort: 8080
              containerPort: 8080
