apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: Local Docker Engine
  type: udm.Environment
  members:
  - Infrastructure/local-docker
---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: rest-o-rant-api-docker
  type: udm.Application
  children:
  - name: '1.1'
    type: udm.DeploymentPackage
    deployables:
    - name: rest-o-rant-network
      type: docker.NetworkSpec
      networkName: rest-o-rant
      driver: bridge
    - name: rest-o-rant-api
      type: docker.ContainerSpec
      image: xebialabsunsupported/rest-o-rant-api
      networks:
      - rest-o-rant
      showLogsAfter: 5
---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: rest-o-rant-web-docker
  type: udm.Application
  children:
  - name: '1.0'
    type: udm.DeploymentPackage
    orchestrator:
    - sequential-by-dependency
    deployables:
    - name: rest-o-rant-web
      type: docker.ContainerSpec
      image: xebialabsunsupported/rest-o-rant-web
      networks:
      - rest-o-rant
      showLogsAfter: 5
      portBindings:
      - name: ports
        type: docker.PortSpec
        hostPort: 8181
        containerPort: 80
        protocol: tcp
---
apiVersion: xl-release/v1
kind: Templates
spec:
- directory: REST-o-rant
  children:
  - template: REST-o-rant on Docker
    description: |
      This XL Release template shows how to deploy and undeploy an application to Docker using XL Deploy.
    tags:
    - REST-o-rant
    - Docker
    phases:
    - phase: Deploy
      color: '#ff9e3b'
      tasks:
      - name: Deploy REST-o-rant application backend
        type: xldeploy.Deploy
        server: XL Deploy
        deploymentPackage:  rest-o-rant-api-docker/1.1
        deploymentEnvironment: Environments/Local Docker Engine
      - name: Deploy REST-o-rant application frontend
        type: xldeploy.Deploy
        server: XL Deploy
        deploymentPackage:  rest-o-rant-web-docker/1.0
        deploymentEnvironment: Environments/Local Docker Engine
    - phase: Test
      tasks:
      - name: Test the REST-o-rant application
        type: xlrelease.Task
        team: Release Admin
        description: |
          The REST-o-rant app is now live on your local Docker Engine. Open the following link in a new browser tab or window:

          http://localhost:8181/

          You should see a text saying "Find the best restaurants near you!". Type "Cow" in the search bar and click "Search" to find the "Old Red Cow" restaurant.

          When everything looks OK, complete this task to continue the release and undeploy the application.
    - phase: Clean up
      color: '#999999'
      tasks:
      - name: Undeploy REST-o-rant application frontend
        type: xldeploy.Undeploy
        server: XL Deploy
        deployedApplication: Environments/Local Docker Engine/rest-o-rant-web-docker
      - name: Undeploy REST-o-rant application backend
        type: xldeploy.Undeploy
        server: XL Deploy
        deployedApplication: Environments/Local Docker Engine/rest-o-rant-api-docker
