
apiVersion: xl-release/v1beta1
kind: Templates
spec:
- directory: Cool Store
  children:
  - directory: Address book
    children:
  - directory: Shopping cart
    children:
  - directory: Wish list
    children:

- directory: Set up
  children:
  - name: Set up Cool Store release train
    type: xlrelease.Release
    description: |
      Follow the steps in this template after starting up.
    scriptUsername: admin
    scriptUserPassword: admin

    phases:
    - name: Create Release Train
      type: xlrelease.Phase
      tasks:
      - name: Cool Store Release
        type: xlrelease.CreateReleaseTask
        newReleaseTitle: Cool Store September delivery
        templateId: JenkinsWorld/Release train process
        folderId: Cool Store
        releaseTags:
        - Cool Store
      - name: Address book
        type: xlrelease.SequentialGroup
        tasks:
        - name: Address book
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: Address book
          templateId: JenkinsWorld/Component delivery process
          folderId: Cool Store/Address book
          releaseTags:
          - Address book
        - name: COOL-113
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: COOL-113
          templateId: JenkinsWorld/Feature delivery process
          folderId: Cool Store/Address book
          templateVariables:
          - key: targetComponent
            type: xlrelease.StringVariable
            value: Address book
        - name: COOL-269
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: COOL-269
          templateId: JenkinsWorld/Feature delivery process
          folderId: Cool Store/Address book
          templateVariables:
          - key: targetComponent
            type: xlrelease.StringVariable
            value: Address book
        - name: COOL-300
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: COOL-300
          templateId: JenkinsWorld/Feature delivery process
          folderId: Cool Store/Address book
          templateVariables:
          - key: targetComponent
            type: xlrelease.StringVariable
            value: Address book

      - name: Shopping cart
        type: xlrelease.SequentialGroup
        tasks:
        - name: Shopping cart
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: Shopping cart
          templateId: JenkinsWorld/Component delivery process
          folderId: Cool Store/Shopping cart
          releaseTags:
          - Shopping cart
        - name: COOL-169
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: COOL-169
          templateId: JenkinsWorld/Feature delivery process
          folderId: Cool Store/Shopping cart
          templateVariables:
          - key: targetComponent
            type: xlrelease.StringVariable
            value: Shopping cart
        - name: COOL-234
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: COOL-234
          templateId: JenkinsWorld/Feature delivery process
          folderId: Cool Store/Shopping cart
          templateVariables:
          - key: targetComponent
            type: xlrelease.StringVariable
            value: Shopping cart

      - name: Wish list
        type: xlrelease.SequentialGroup
        tasks:
        - name: Wish list
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: Wish list
          templateId: JenkinsWorld/Component delivery process
          folderId: Cool Store/Wish list
          releaseTags:
          - Wish list
        - name: COOL-235
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: COOL-235
          templateId: JenkinsWorld/Feature delivery process
          folderId: Cool Store/Wish list
          templateVariables:
          - key: targetComponent
            type: xlrelease.StringVariable
            value: Wish list
        - name: COOL-268
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: COOL-268
          templateId: JenkinsWorld/Feature delivery process
          folderId: Cool Store/Wish list
          templateVariables:
          - key: targetComponent
            type: xlrelease.StringVariable
            value: Wish list
        - name: COOL-301
          type: xlrelease.CreateReleaseTask
          newReleaseTitle: COOL-301
          templateId: JenkinsWorld/Feature delivery process
          folderId: Cool Store/Wish list
          templateVariables:
          - key: targetComponent
            type: xlrelease.StringVariable
            value: Wish list

    - name: Import Jenkins Pipelines
      type: xlrelease.Phase
      tasks:
      - name: Import Address book
        type: xlrelease.CreateReleaseTask
        newReleaseTitle: Import Address book pipeline
        templateId: JenkinsWorld/Import Jenkins pipelines
        folderId: Cool Store/Address book
        templateVariables:
        - key: jenkinsFolder
          value: Cool Store/Address book
          type: xlrelease.StringVariable
        - key: targetFolder
          value: Cool Store/Address book
          type: xlrelease.StringVariable
        - key: masterTemplate
          value: JenkinsWorld/Track Jenkins pipeline
          type: xlrelease.StringVariable
        - key: enableTrigger
          value: true
          type: xlrelease.BooleanVariable
      - name: Import Shopping cart
        type: xlrelease.CreateReleaseTask
        newReleaseTitle: Import Shopping cart pipeline
        templateId: JenkinsWorld/Import Jenkins pipelines
        folderId: Cool Store/Shopping cart
        templateVariables:
        - key: jenkinsFolder
          value: Cool Store/Shopping cart
          type: xlrelease.StringVariable
        - key: targetFolder
          value: Cool Store/Shopping cart
          type: xlrelease.StringVariable
        - key: masterTemplate
          value: JenkinsWorld/Track Jenkins pipeline
          type: xlrelease.StringVariable
        - key: enableTrigger
          value: true
          type: xlrelease.BooleanVariable
      - name: Import Wish list
        type: xlrelease.CreateReleaseTask
        newReleaseTitle: Import Wish list pipeline
        templateId: JenkinsWorld/Import Jenkins pipelines
        folderId: Cool Store/Wish list
        templateVariables:
        - key: jenkinsFolder
          value: Cool Store/Wish list
          type: xlrelease.StringVariable
        - key: targetFolder
          value: Cool Store/Wish list
          type: xlrelease.StringVariable
        - key: masterTemplate
          value: JenkinsWorld/Track Jenkins pipeline
          type: xlrelease.StringVariable
        - key: enableTrigger
          value: true
          type: xlrelease.BooleanVariable

---
apiVersion: xl-release/v1beta1
kind: Release
spec:
  name: Set up Cool Store demo
  template: Set up/Set up Cool Store release train
  variables: # TODO remove this with alpha.12 of the XL client
    version: '1.0'
