
apiVersion: xl-release/v1beta1
kind: Templates
spec:
- directory: JenkinsWorld
  children:
  - name: Release train process
    type: xlrelease.Release
    scheduledStartDate: '2018-08-16'
    variables:
    - key: jiraTicket
      type: xlrelease.StringVariable
      requiresValue: false
      showOnReleaseStart: false

    phases:

    - name: Dev
      type: xlrelease.Phase
      color: '#08B153'
      tasks:
      - name: Wait for components
        type: xlrelease.GateTask
        tags:
        - Components

    - name: Acceptance
      type: xlrelease.Phase
      color: '#FD8D10'
      tasks:
      - name: Open JIRA Request for QA
        type: jira.CreateIssue
        project: SAN
        ^title: ${release.title}
        description: |
          Release process for ${release.title} has started.

          ${release.title} has been deployed to TEST.

          Put this ticket in progress to approve testing cycle.
        issueId: ${jiraTicket}
      - name: Wait for approval for deployment to test
        type: jira.CheckQuery
        query: issue = ${jiraTicket}
        expectedStatus: In Progress
        pollInterval: 10
      - name: Deploy to TEST
        type: xldeploy.Deploy
        taskFailureHandlerEnabled: true
        taskRecoverOp: SKIP_TASK
      - name: Add comment to change request
        type: jira.UpdateIssue
        issueId: ${jiraTicket}
        comment: Tests have passed successfully.
      - name: Perform Automated Testing
        type: xlrelease.ParallelGroup
        tasks:
        - name: UI tests
          type: xlrelease.ScriptTask
          script: |
            import time
            time.sleep(5)
        - name: Integration tests
          type: xlrelease.ScriptTask
          script: |
            import time
            time.sleep(15)
      - name: Close JIRA ticket
        type: jira.UpdateIssue
        issueId: ${jiraTicket}
        newStatus: Resolved
        comment: ${release.title} was deployed to PROD.

    - name: Release Preparation
      type: xlrelease.Phase
      color: '#0099CC'
      tasks:
      - name: Notify Product Marketing that release is starting
        type: xlrelease.NotificationTask
        taskFailureHandlerEnabled: true
        taskRecoverOp: SKIP_TASK
      - name: Verify all preconditions are met
        type: xlrelease.ParallelGroup
        tasks:
        - name: All stories that are in the release are DONE
          type: xlrelease.GateTask

        - name: JIRA administration is done
          type: xlrelease.GateTask

        - name: Technical documentation is up-to-date
          type: xlrelease.GateTask

      - name: Update release notes
        type: remoteScript.Unix

    - name: Release to PROD
      type: xlrelease.Phase
      color: '#0099CC'
      tasks:
      - name: Authorize PROD deployment
        type: xlrelease.GateTask

      - name: Create Service Now request
        type: servicenow.CreateChangeRequest
        taskFailureHandlerEnabled: true
        taskRecoverOp: SKIP_TASK

      - name: Wait for approval through Service Now
        type: servicenow.CreateChangeRequest
        taskFailureHandlerEnabled: true
        taskRecoverOp: SKIP_TASK

      - name: Deploy to PROD
        type: xldeploy.Deploy
        taskFailureHandlerEnabled: true
        taskRecoverOp: SKIP_TASK
#        retryCounter:
#          currentContinueRetrial:0
#          currentPollingTrial:0
      - name: Add comment to request
        type: servicenow.CreateChangeRequest
        taskFailureHandlerEnabled: true
        taskRecoverOp: SKIP_TASK

      - name: Run Smoke Tests
        type: remoteScript.Unix

      - name: Close Service Now request
        type: servicenow.CreateChangeRequest
        taskFailureHandlerEnabled: true
        taskRecoverOp: SKIP_TASK

    - name: Publish release
      type: xlrelease.Phase
      color: '#0099CC'
      tasks:
      - name: Create escrow
        type: xlrelease.CreateReleaseTask

      - name: Publish documentation
        type: xlrelease.Task

      - name: Send annoncements
        type: xlrelease.ParallelGroup
        tasks:
        - name: Publish on forum
          type: xlrelease.NotificationTask

        - name: Tell Marketing to send out email blast
          type: xlrelease.NotificationTask

        - name: Update info on web site
          type: xlrelease.Task

      - name: Update list of supported versions
        type: xlrelease.Task
