apiVersion: xl-release/v1beta1
kind: Configurations
spec:
- name: Jenkins localhost
  type: jenkins.Server
  url: http://jenkins:8080/
  username: admin
  password: admin
---
apiVersion: xl-release/v1beta1
kind: Configurations
spec:
- name: Jira Server
  type: jira.Server
  url: !value jira.url
  username: !value jira.user
  password: !secret jira.password
---
apiVersion: xl-release/v1beta1
kind: Configurations
spec:
- name: Fortify
  type: fortifyOnDemand.Server
  url: !value fortify.url
  username: !value fortify.user
  password: !secret fortify.password
---
apiVersion: xl-release/v1beta1
kind: Configurations
spec:
- name: Checkmarx
  type: checkmarx.Server
  url: !value checkmarx.url
  username: !value checkmarx.user
  password: !secret checkmarx.password
