apiVersion: xl-release/v1beta1
kind: Configurations
spec:
- name: Jenkins localhost
  type: jenkins.Server
  url: http://jenkins:8080/
  username: admin
  password: admin
---
apiVersion: xl-release/v1beta1
kind: Configurations
spec:
- name: Jira Server
  type: jira.Server
  url: https://xebialabs.atlassian.net/
  username: hsiemelink
  password: secret
---
apiVersion: xl-release/v1beta1
kind: Configurations
spec:
- name: Fortify
  type: fortifyOnDemand.Server
  url: https://api.emea.fortify.com/
  username: xebialabs\hsiemelink
  password: '#UMrw6.W.}9Ks6[MP2'

