version: '2.3'
services:
  jenkins:
    image: jenkinsci/blueocean:latest
    container_name: jenkins2
    ports:
    - 8081:8080
    - 50000:50000
    volumes:
    - ./storage:/var/jenkins_home
    networks:
    - jenkinsworld_default
    environment:
    - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

networks:
  jenkinsworld_default:
    external: true
