version: '2.3'
services:
  xl-deploy:
    image: xl-docker.xebialabs.com:443/xl-deploy:8.2.0-alpha.38
    ports:
    - "14516:4516"
    volumes:
    - ~/.xl-config/deployit-license.lic:/opt/xebialabs/xl-deploy-server/conf/deployit-license.lic:ro
    - ../../docker/volumes/xld/hotfix/plugins:/opt/xebialabs/xl-deploy-server/hotfix/plugins:ro
    # Workaround for bug (in XL Deploy?) that causes plugins to not function correctly if loaded from within the container
    - ../../docker/volumes/xld/plugins:/opt/xebialabs/xl-deploy-server/plugins
    environment:
    - ADMIN_PASSWORD=3dm1n

  xl-release:
    image: xl-docker.xebialabs.com:443/xl-release:8.1.1-alpha.13
    ports:
    - "15516:5516"
    depends_on:
    - xl-deploy
    volumes:
    - ~/.xl-config/xl-release-license.lic:/opt/xebialabs/xl-release-server/conf/xl-release-license.lic:ro
    - ../../docker/volumes/xlr/hotfix:/opt/xebialabs/xl-release-server/hotfix:ro
    environment:
    - ADMIN_PASSWORD=3dm2n

  xl-cli:
    build: ../../docker/xl-cli
    depends_on:
    - xl-deploy
    - xl-release
    command: ["apply", "--url", "http://admin:admin@xl-release:5516/ascode", "-f", "/data/config/link-xl-release-to-xl-deploy.yaml"]
    volumes:
    - ../..:/data:ro
