apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: Simple Docker container
  description: This blueprint defines an application that consists of a single container to be start on a Docker engine
  author: XebiaLabs
  version: '1.0'
spec:
- name: Image
  type: Input
  description: What is the Docker image to deploy?
- name: ShowLogsAfter
  type: Input
  description: How many seconds should we wait before retrieving the container logs?
  default: 10
- name: PublishAllPorts
  type: Confirm
  description: Should all ports be exposed?
  default: true