apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: Simple Docker container
  description: This blueprint defines an application that consists of a single container to be start on a Docker engine
  author: XebiaLabs
  version: '1.0'
spec:

- name: ApplicationName
  type: Input
  description: What is the Application name?
- name: Image
  type: Input
  description: What is the Docker image to deploy?
